#!/bin/bash
# Setup GitHub remote for AVA OLO project

echo "🔗 Setting up GitHub remote for AVA OLO"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Create a new repository on GitHub:"
echo "   - Go to https://github.com/new"
echo "   - Repository name: ava-olo-constitutional"
echo "   - Description: AVA OLO Agricultural Intelligence with Constitutional Design System"
echo "   - Make it private or public as needed"
echo "   - DO NOT initialize with README (we already have files)"
echo ""
echo "2. After creating the repository, run these commands:"
echo ""
echo "   # Add the remote (replace YOUR_USERNAME with your GitHub username)"
echo "   git remote add origin https://github.com/YOUR_USERNAME/ava-olo-constitutional.git"
echo ""
echo "   # Push the code and tags"
echo "   git push -u origin master"
echo "   git push origin --tags"
echo ""
echo "3. Add GitHub Secrets for deployment:"
echo "   Go to Settings > Secrets and variables > Actions"
echo "   Add these secrets:"
echo "   - AWS_ACCESS_KEY_ID"
echo "   - AWS_SECRET_ACCESS_KEY"
echo ""
echo "4. The GitHub Actions workflow will automatically:"
echo "   - Build Docker images on every push"
echo "   - Push to ECR"
echo "   - Deploy to ECS"
echo ""
echo "5. Verify deployment:"
echo "   - Check Actions tab on GitHub"
echo "   - Visit https://ava-olo-alb-65365776.us-east-1.elb.amazonaws.com/"
echo ""
echo "📝 Note: All future deployments will happen automatically on git push!"